### ISSUE TITLE
Ingest test failure - "no gdaljni in java.library.path"

### ISSUE THREAD

**Issue by jwalgran** [geotrellis/vagrant.geotrellis#4]
I tried provisioning with the addition of `azavea.libgdal-java` but that was not enough:

```
[info] Ingest
[info] - should ingest GeoTiff
Native library load failed.
java.lang.UnsatisfiedLinkError: no gdaljni in java.library.path
00:54:28 Executor: Exception in task 0.0 in stage 432.0 (TID 1630)
java.lang.UnsatisfiedLinkError: org.gdal.gdal.gdalJNI.AllRegister()V
    at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
    at org.gdal.gdal.gdal.AllRegister(gdal.java:499)
    at geotrellis.gdal.Gdal$.<init>(Gdal.scala:17)
    at geotrellis.gdal.Gdal$.<clinit>(Gdal.scala)
    at geotrellis.spark.io.hadoop.formats.GdalRecordReader.initialize(GdalInputFormat.scala:102)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:135)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:107)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
    at org.apache.spark.scheduler.Task.run(Task.scala:56)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
00:54:28 SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-4,5,main]
java.lang.UnsatisfiedLinkError: org.gdal.gdal.gdalJNI.AllRegister()V
    at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
    at org.gdal.gdal.gdal.AllRegister(gdal.java:499)
    at geotrellis.gdal.Gdal$.<init>(Gdal.scala:17)
    at geotrellis.gdal.Gdal$.<clinit>(Gdal.scala)
    at geotrellis.spark.io.hadoop.formats.GdalRecordReader.initialize(GdalInputFormat.scala:102)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:135)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:107)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
    at org.apache.spark.scheduler.Task.run(Task.scala:56)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
00:54:28 TaskSetManager: Lost task 0.0 in stage 432.0 (TID 1630, localhost): java.lang.UnsatisfiedLinkError: org.gdal.gdal.gdalJNI.AllRegister()V
    at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
    at org.gdal.gdal.gdal.AllRegister(gdal.java:499)
    at geotrellis.gdal.Gdal$.<init>(Gdal.scala:17)
    at geotrellis.gdal.Gdal$.<clinit>(Gdal.scala)
    at geotrellis.spark.io.hadoop.formats.GdalRecordReader.initialize(GdalInputFormat.scala:102)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:135)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:107)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
    at org.apache.spark.scheduler.Task.run(Task.scala:56)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

00:54:28 TaskSetManager: Task 0 in stage 432.0 failed 1 times; aborting job
Exception in thread "Thread-1" Exception in thread "Thread-5" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at sbt.React.react(ForkTests.scala:117)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:76)
    at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:945)
    at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:934)
    at java.lang.Thread.run(Thread.java:745)
[info] Run completed in 2 minutes, 14 seconds.
[info] Total number of tests run: 87
[info] Suites: completed 25, aborted 0
[info] Tests: succeeded 87, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error during tests:
[error]     Running java with options -classpath /home/vagrant/geotrellis/spark/target/scala-2.11/test-classes:/home/vagrant/geotrellis/spark/target/scala-2.11/classes:/home/vagrant/geotrellis/raster/target/scala-2.11/classes:/home/vagrant/geotrellis/macros/target/scala-2.11/classes:/home/vagrant/geotrellis/vector/target/scala-2.11/classes:/home/vagrant/geotrellis/proj4/target/scala-2.11/classes:/home/vagrant/geotrellis/gdal/target/scala-2.11/classes:/home/vagrant/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar:/home/vagrant/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:/home/vagrant/.ivy2/cache/net.sf.opencsv/opencsv/jars/opencsv-2.3.jar:/home/vagrant/.ivy2/cache/com.vividsolutions/jts/jars/jts-1.13.jar:/home/vagrant/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.1.jar:/home/vagrant/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.2.jar:/home/vagrant/.ivy2/cache/org.spire-math/spire_2.11/jars/spire_2.11-0.7.5.jar:/home/vagrant/.ivy2/cache/org.spire-math/spire-macros_2.11/jars/spire-macros_2.11-0.7.5.jar:/home/vagrant/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/vagrant/.ivy2/cache/com.github.julien-truffaut/monocle-core_2.11/jars/monocle-core_2.11-1.0.1.jar:/home/vagrant/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.0.jar:/home/vagrant/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:/home/vagrant/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/home/vagrant/.ivy2/cache/com.github.julien-truffaut/monocle-macro_2.11/jars/monocle-macro_2.11-1.0.1.jar:/home/vagrant/.ivy2/cache/org.gdal/gdal/jars/gdal-1.10.1.jar:/home/vagrant/.ivy2/cache/com.github.scopt/scopt_2.10/jars/scopt_2.10-3.2.0.jar:/home/vagrant/.ivy2/cache/com.quantifind/sumac_2.11/jars/sumac_2.11-0.3.0.jar:/home/vagrant/.ivy2/cache/org.apache.accumulo/accumulo-core/jars/accumulo-core-1.5.2.jar:/home/vagrant/.ivy2/cache/com.beust/jcommander/jars/jcommander-1.30.jar:/home/vagrant/.ivy2/cache/com.google.guava/guava/bundles/guava-14.0.1.jar:/home/vagrant/.ivy2/cache/jline/jline/jars/jline-1.0.jar:/home/vagrant/.ivy2/cache/org.apache.accumulo/accumulo-fate/jars/accumulo-fate-1.5.2.jar:/home/vagrant/.ivy2/cache/org.apache.accumulo/accumulo-start/jars/accumulo-start-1.5.2.jar:/home/vagrant/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/vagrant/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/vagrant/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/vagrant/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/vagrant/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/vagrant/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/vagrant/.ivy2/cache/org.apache.accumulo/accumulo-trace/jars/accumulo-trace-1.5.2.jar:/home/vagrant/.ivy2/cache/org.apache.thrift/libthrift/jars/libthrift-0.9.0.jar:/home/vagrant/.ivy2/cache/org.apache.commons/commons-math/jars/commons-math-2.1.jar:/home/vagrant/.ivy2/cache/de.javakaffee/kryo-serializers/bundles/kryo-serializers-0.27.jar:/home/vagrant/.ivy2/cache/com.esotericsoftware.kryo/kryo/bundles/kryo-2.24.0.jar:/home/vagrant/.ivy2/cache/com.esotericsoftware.minlog/minlog/jars/minlog-1.2.jar:/home/vagrant/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-2.1.jar:/home/vagrant/.ivy2/cache/com.typesafe.scala-logging/scala-logging-slf4j_2.11/jars/scala-logging-slf4j_2.11-2.1.2.jar:/home/vagrant/.ivy2/cache/com.typesafe.scala-logging/scala-logging-api_2.11/jars/scala-logging-api_2.11-2.1.2.jar:/home/vagrant/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.7.jar:/home/vagrant/.ivy2/cache/com.amazonaws/aws-java-sdk-s3/jars/aws-java-sdk-s3-1.9.16.jar:/home/vagrant/.ivy2/cache/com.amazonaws/aws-java-sdk-kms/jars/aws-java-sdk-kms-1.9.16.jar:/home/vagrant/.ivy2/cache/com.amazonaws/aws-java-sdk-core/jars/aws-java-sdk-core-1.9.16.jar:/home/vagrant/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar:/home/vagrant/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.3.4.jar:/home/vagrant/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.3.2.jar:/home/vagrant/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.6.jar:/home/vagrant/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.2.jar:/home/vagrant/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.0.jar:/home/vagrant/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.2.jar:/home/vagrant/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.7.jar:/home/vagrant/.ivy2/cache/com.github.nscala-time/nscala-time_2.11/jars/nscala-time_2.11-1.6.0.jar:/home/vagrant/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.2.jar:/home/vagrant/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-2.2.0.jar:/home/vagrant/.ivy2/cache/org.apache.spark/spark-core_2.11/jars/spark-core_2.11-1.2.0.jar:/home/vagrant/.ivy2/cache/com.twitter/chill_2.11/jars/chill_2.11-0.5.0.jar:/home/vagrant/.ivy2/cache/com.twitter/chill-java/jars/chill-java-0.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-client/jars/hadoop-client-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-common/jars/hadoop-common-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-annotations/jars/hadoop-annotations-2.5.0.jar:/home/vagrant/.ivy2/cache/commons-cli/commons-cli/jars/commons-cli-1.2.jar:/home/vagrant/.ivy2/cache/xmlenc/xmlenc/jars/xmlenc-0.52.jar:/home/vagrant/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar:/home/vagrant/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/home/vagrant/.ivy2/cache/commons-net/commons-net/jars/commons-net-3.1.jar:/home/vagrant/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar:/home/vagrant/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.17.jar:/home/vagrant/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/vagrant/.ivy2/cache/commons-configuration/commons-configuration/jars/commons-configuration-1.6.jar:/home/vagrant/.ivy2/cache/commons-digester/commons-digester/jars/commons-digester-1.8.jar:/home/vagrant/.ivy2/cache/commons-beanutils/commons-beanutils/jars/commons-beanutils-1.7.0.jar:/home/vagrant/.ivy2/cache/commons-beanutils/commons-beanutils-core/jars/commons-beanutils-core-1.8.0.jar:/home/vagrant/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.9.13.jar:/home/vagrant/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.9.13.jar:/home/vagrant/.ivy2/cache/org.apache.avro/avro/jars/avro-1.7.4.jar:/home/vagrant/.ivy2/cache/org.apache.commons/commons-compress/jars/commons-compress-1.4.1.jar:/home/vagrant/.ivy2/cache/org.tukaani/xz/jars/xz-1.0.jar:/home/vagrant/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-auth/jars/hadoop-auth-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.directory.server/apacheds-kerberos-codec/bundles/apacheds-kerberos-codec-2.0.0-M15.jar:/home/vagrant/.ivy2/cache/org.apache.directory.server/apacheds-i18n/bundles/apacheds-i18n-2.0.0-M15.jar:/home/vagrant/.ivy2/cache/org.apache.directory.api/api-asn1-api/bundles/api-asn1-api-1.0.0-M20.jar:/home/vagrant/.ivy2/cache/org.apache.directory.api/api-util/bundles/api-util-1.0.0-M20.jar:/home/vagrant/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-hdfs/jars/hadoop-hdfs-2.5.0.jar:/home/vagrant/.ivy2/cache/org.mortbay.jetty/jetty-util/jars/jetty-util-6.1.26.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-app/jars/hadoop-mapreduce-client-app-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-common/jars/hadoop-mapreduce-client-common-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-yarn-common/jars/hadoop-yarn-common-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-yarn-api/jars/hadoop-yarn-api-2.5.0.jar:/home/vagrant/.ivy2/cache/javax.xml.bind/jaxb-api/jars/jaxb-api-2.2.2.jar:/home/vagrant/.ivy2/cache/javax.xml.stream/stax-api/jars/stax-api-1.0-2.jar:/home/vagrant/.ivy2/cache/javax.activation/activation/jars/activation-1.1.jar:/home/vagrant/.ivy2/cache/com.sun.jersey/jersey-core/bundles/jersey-core-1.9.jar:/home/vagrant/.ivy2/cache/org.codehaus.jackson/jackson-jaxrs/jars/jackson-jaxrs-1.9.13.jar:/home/vagrant/.ivy2/cache/org.codehaus.jackson/jackson-xc/jars/jackson-xc-1.9.13.jar:/home/vagrant/.ivy2/cache/com.google.inject/guice/jars/guice-3.0.jar:/home/vagrant/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/home/vagrant/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:/home/vagrant/.ivy2/cache/org.sonatype.sisu.inject/cglib/jars/cglib-2.2.1-v20090111.jar:/home/vagrant/.ivy2/cache/asm/asm/jars/asm-3.2.jar:/home/vagrant/.ivy2/cache/com.sun.jersey/jersey-server/bundles/jersey-server-1.9.jar:/home/vagrant/.ivy2/cache/com.sun.jersey/jersey-json/bundles/jersey-json-1.9.jar:/home/vagrant/.ivy2/cache/org.codehaus.jettison/jettison/bundles/jettison-1.1.jar:/home/vagrant/.ivy2/cache/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.2.3-1.jar:/home/vagrant/.ivy2/cache/com.sun.jersey.contribs/jersey-guice/jars/jersey-guice-1.9.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-yarn-client/jars/hadoop-yarn-client-2.5.0.jar:/home/vagrant/.ivy2/cache/com.sun.jersey/jersey-client/bundles/jersey-client-1.9.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-core/jars/hadoop-mapreduce-client-core-2.5.0.jar:/home/vagrant/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-yarn-server-common/jars/hadoop-yarn-server-common-2.5.0.jar:/home/vagrant/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni-all/bundles/leveldbjni-all-1.8.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-shuffle/jars/hadoop-mapreduce-client-shuffle-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-jobclient/jars/hadoop-mapreduce-client-jobclient-2.5.0.jar:/home/vagrant/.ivy2/cache/org.apache.spark/spark-network-common_2.11/jars/spark-network-common_2.11-1.2.0.jar:/home/vagrant/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.23.Final.jar:/home/vagrant/.ivy2/cache/org.spark-project.spark/unused/jars/unused-1.0.0.jar:/home/vagrant/.ivy2/cache/org.apache.spark/spark-network-shuffle_2.11/jars/spark-network-shuffle_2.11-1.2.0.jar:/home/vagrant/.ivy2/cache/net.java.dev.jets3t/jets3t/jars/jets3t-0.7.1.jar:/home/vagrant/.ivy2/cache/org.apache.curator/curator-recipes/bundles/curator-recipes-2.4.0.jar:/home/vagrant/.ivy2/cache/org.apache.curator/curator-framework/bundles/curator-framework-2.4.0.jar:/home/vagrant/.ivy2/cache/org.apache.curator/curator-client/bundles/curator-client-2.4.0.jar:/home/vagrant/.ivy2/cache/org.apache.zookeeper/zookeeper/jars/zookeeper-3.4.5.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-plus/jars/jetty-plus-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty.orbit/javax.transaction/orbits/javax.transaction-1.1.1.v201105210645.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-webapp/jars/jetty-webapp-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-xml/jars/jetty-xml-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-util/jars/jetty-util-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-servlet/jars/jetty-servlet-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-security/jars/jetty-security-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-server/jars/jetty-server-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty.orbit/javax.servlet/orbits/javax.servlet-3.0.0.v201112011016.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-continuation/jars/jetty-continuation-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-http/jars/jetty-http-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-io/jars/jetty-io-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty/jetty-jndi/jars/jetty-jndi-8.1.14.v20131031.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty.orbit/javax.mail.glassfish/orbits/javax.mail.glassfish-1.4.1.v201005082020.jar:/home/vagrant/.ivy2/cache/org.eclipse.jetty.orbit/javax.activation/orbits/javax.activation-1.1.0.v201105071233.jar:/home/vagrant/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.3.2.jar:/home/vagrant/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.5.jar:/home/vagrant/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.5.jar:/home/vagrant/.ivy2/cache/com.ning/compress-lzf/bundles/compress-lzf-1.0.0.jar:/home/vagrant/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.1.1.6.jar:/home/vagrant/.ivy2/cache/net.jpountz.lz4/lz4/jars/lz4-1.2.0.jar:/home/vagrant/.ivy2/cache/org.roaringbitmap/RoaringBitmap/bundles/RoaringBitmap-0.4.5.jar:/home/vagrant/.ivy2/cache/org.spark-project.akka/akka-remote_2.11/jars/akka-remote_2.11-2.3.4-spark.jar:/home/vagrant/.ivy2/cache/org.spark-project.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.4-spark.jar:/home/vagrant/.ivy2/cache/io.netty/netty/bundles/netty-3.8.0.Final.jar:/home/vagrant/.ivy2/cache/org.spark-project.protobuf/protobuf-java/bundles/protobuf-java-2.5.0-spark.jar:/home/vagrant/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:/home/vagrant/.ivy2/cache/org.spark-project.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.4-spark.jar:/home/vagrant/.ivy2/cache/org.json4s/json4s-jackson_2.11/jars/json4s-jackson_2.11-3.2.10.jar:/home/vagrant/.ivy2/cache/org.json4s/json4s-core_2.11/jars/json4s-core_2.11-3.2.10.jar:/home/vagrant/.ivy2/cache/org.json4s/json4s-ast_2.11/jars/json4s-ast_2.11-3.2.10.jar:/home/vagrant/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/home/vagrant/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.0.jar:/home/vagrant/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0.jar:/home/vagrant/.ivy2/cache/org.apache.mesos/mesos/jars/mesos-0.18.1-shaded-protobuf.jar:/home/vagrant/.ivy2/cache/com.clearspring.analytics/stream/jars/stream-2.7.0.jar:/home/vagrant/.ivy2/cache/com.codahale.metrics/metrics-core/bundles/metrics-core-3.0.0.jar:/home/vagrant/.ivy2/cache/com.codahale.metrics/metrics-jvm/bundles/metrics-jvm-3.0.0.jar:/home/vagrant/.ivy2/cache/com.codahale.metrics/metrics-json/bundles/metrics-json-3.0.0.jar:/home/vagrant/.ivy2/cache/com.codahale.metrics/metrics-graphite/bundles/metrics-graphite-3.0.0.jar:/home/vagrant/.ivy2/cache/org.tachyonproject/tachyon-client/jars/tachyon-client-0.5.0.jar:/home/vagrant/.ivy2/cache/org.tachyonproject/tachyon/jars/tachyon-0.5.0.jar:/home/vagrant/.ivy2/cache/org.spark-project/pyrolite/jars/pyrolite-2.0.1.jar:/home/vagrant/.ivy2/cache/net.sf.py4j/py4j/jars/py4j-0.8.2.1.jar:/home/vagrant/.ivy2/cache/javax.servlet/servlet-api/jars/servlet-api-2.5.jar:/home/vagrant/.sbt/0.13.5/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.5/test-agent-0.13.5.jar:/home/vagrant/.sbt/0.13.5/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.5/test-interface-1.0.jar sbt.ForkMain 32928 failed with exit code 50
[error] (spark/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 485 s, completed Mar 26, 2015 12:54:29 AM
```

**Comment by notthatbreezy** [comment]
Started to look into this - not sure what is up with it though yet. @lossyrob or @echeipesh might have a better idea
